const board = document.querySelector('#board');
const roster = document.querySelector('#roster');
const detail = document.querySelector('#unit-detail');
const status = document.querySelector('#status');
const endTurn = document.querySelector('#end-turn');
const restart = document.querySelector('#restart');
const turnBadge = document.querySelector('#turn-badge');
const prisonerCount = document.querySelector('#prisoner-count');
const resultDialog = document.querySelector('#result-dialog');
const resultContent = document.querySelector('#result-content');

const baseUnits = [
  { id:'warden', team:'player', name:'Guardia del Roble', type:'Torre', icon:'♜', x:1, y:6, hp:6, maxHp:6, damage:2, range:'orthogonal', ability:'Baluarte', description:'Se mueve en líneas rectas. Su golpe pesado puede derribar.' },
  { id:'seer', team:'player', name:'Vidente de Musgo', type:'Alfil', icon:'♝', x:3, y:7, hp:4, maxHp:4, damage:1, range:'diagonal', ability:'Enredadera', description:'Se mueve en diagonal. Inflige +1 daño a enemigos adyacentes a un aliado.' },
  { id:'scout', team:'player', name:'Exploradora', type:'Peón arquero', icon:'♟', x:5, y:6, hp:3, maxHp:3, damage:1, range:'scout', ability:'Red de caza', description:'Avanza una casilla; ataca a distancia hasta dos casillas en diagonal.' },
  { id:'brute', team:'enemy', name:'Bruto de Ceniza', type:'Torre', icon:'♜', x:6, y:1, hp:5, maxHp:5, damage:2, range:'orthogonal', ability:'Carga brutal', description:'Un guerrero pesado de la banda rival.' },
  { id:'hexer', team:'enemy', name:'Tejedora Escarlata', type:'Alfil', icon:'♝', x:4, y:0, hp:3, maxHp:3, damage:1, range:'diagonal', ability:'Maldición', description:'Conjura desde las diagonales.' },
  { id:'raider', team:'enemy', name:'Saqueador', type:'Peón', icon:'♟', x:2, y:1, hp:3, maxHp:3, damage:1, range:'scout', ability:'Golpe bajo', description:'Un explorador que busca flancos.' }
];

let units, selectedId, currentTurn, prisoners, finished;
const inside = (x,y) => x >= 0 && x < 8 && y >= 0 && y < 8;
const alive = unit => unit.hp > 0 && !unit.captured;
const at = (x,y) => units.find(unit => alive(unit) && unit.x === x && unit.y === y);
const selected = () => units.find(unit => unit.id === selectedId);

function reset() { units = structuredClone(baseUnits); selectedId = null; currentTurn = 'player'; prisoners = []; finished = false; resultDialog.close(); render(); setStatus('Selecciona una unidad de tu banda. Las casillas verdes indican movimiento; las rojas, ataque.'); }
function setStatus(message) { status.textContent = message; }
function validLineMoves(unit, directions, max=7) { const moves=[]; for (const [dx,dy] of directions) for(let step=1; step<=max; step++) { const x=unit.x+dx*step,y=unit.y+dy*step; if(!inside(x,y)) break; const occupant=at(x,y); if(occupant) { if(occupant.team !== unit.team) moves.push({x,y,kind:occupant.hp===1?'capture':'attack'}); break; } moves.push({x,y,kind:'move'}); } return moves; }
function optionsFor(unit) { if (!unit || !alive(unit) || unit.team !== currentTurn) return []; if (unit.range === 'orthogonal') return validLineMoves(unit,[[1,0],[-1,0],[0,1],[0,-1]],3); if (unit.range === 'diagonal') return validLineMoves(unit,[[1,1],[1,-1],[-1,1],[-1,-1]],3); const moves=[]; [[0,-1],[1,-1],[-1,-1],[1,0],[-1,0]].forEach(([dx,dy])=>{const x=unit.x+dx,y=unit.y+dy;if(!inside(x,y))return;const occupant=at(x,y);if(!occupant)moves.push({x,y,kind:'move'});else if(occupant.team!==unit.team)moves.push({x,y,kind:occupant.hp===1?'capture':'attack'});}); [[1,-1],[-1,-1],[1,1],[-1,1]].forEach(([dx,dy])=>{const x=unit.x+dx*2,y=unit.y+dy*2;const target=at(x,y);if(inside(x,y)&&target&&target.team!==unit.team)moves.push({x,y,kind:target.hp===1?'capture':'attack'});}); return moves; }
function perform(unit, option) { const target = at(option.x, option.y); if(option.kind === 'move') { unit.x=option.x; unit.y=option.y; setStatus(`${unit.name} se reposiciona.`); } else if(option.kind === 'attack') { target.hp=Math.max(1,target.hp-unit.damage); setStatus(`${unit.name} hiere a ${target.name}. Queda vulnerable: redúcelo a 1 de salud para capturarlo.`); } else { target.hp=0; target.captured=true; prisoners.push(target); setStatus(`${target.name} ha sido sometido. Podrás reclutarlo si vences.`); } selectedId=null; checkEnd(); render(); }
function enemyTurn() { if(finished) return; currentTurn='enemy'; render(); setStatus('La banda rival se mueve…'); setTimeout(()=> { const enemies=units.filter(u=>alive(u)&&u.team==='enemy'); const players=units.filter(u=>alive(u)&&u.team==='player'); if(!enemies.length||!players.length) return; const enemy=enemies[Math.floor(Math.random()*enemies.length)]; const opts=optionsFor(enemy); const attacks=opts.filter(o=>o.kind!=='move'); const choice=attacks[0] || opts[Math.floor(Math.random()*opts.length)]; if(choice) { const target=at(choice.x,choice.y); if(choice.kind==='move') { enemy.x=choice.x; enemy.y=choice.y; setStatus(`${enemy.name} busca una posición mejor.`); } else if(choice.kind==='capture') { target.hp=0; target.captured=true; setStatus(`${enemy.name} ha eliminado a ${target.name}.`); } else { target.hp=Math.max(1,target.hp-enemy.damage); setStatus(`${enemy.name} hiere a ${target.name}.`); } } currentTurn='player'; checkEnd(); render(); if(!finished) setTimeout(()=>setStatus('Tu turno. Elige una unidad.'),500); },550); }
function checkEnd() { const rivals=units.filter(u=>alive(u)&&u.team==='enemy'); const allies=units.filter(u=>alive(u)&&u.team==='player'); if(!rivals.length) finish(true); else if(!allies.length) finish(false); }
function finish(win) { if(finished) return; finished=true; render(); if(win) { const choices=prisoners.filter(u=>u.type!=='Peón'); const recruitText=choices.length ? `<p>Has sometido a ${prisoners.length} rival(es). Elige uno para que se una a tu banda en la siguiente misión:</p>${choices.map(u=>`<button class="recruit-choice" data-id="${u.id}"><strong>${u.icon} ${u.name}</strong><br><small>${u.type} · ${u.ability}</small></button>`).join('')}` : '<p>La banda rival se ha retirado. No hay prisioneros disponibles para reclutar.</p>'; resultContent.innerHTML=`<div class="result-card"><p class="eyebrow">MISIÓN COMPLETADA</p><h2>Victoria</h2>${recruitText}<button class="primary-button" id="play-again">Nueva escaramuza</button></div>`; } else resultContent.innerHTML='<div class="result-card"><p class="eyebrow">LA BANDA HA CAÍDO</p><h2>Derrota</h2><p>Prueba a usar el terreno y a someter a enemigos debilitados antes de perder a tus veteranos.</p><button class="primary-button" id="play-again">Intentarlo de nuevo</button></div>';
 resultDialog.showModal(); document.querySelector('#play-again').addEventListener('click',reset); resultContent.querySelectorAll('[data-id]').forEach(button=>button.addEventListener('click',()=>{ const unit=units.find(u=>u.id===button.dataset.id); button.outerHTML=`<p><strong>${unit.name}</strong> se ha unido a tu banda. (La progresión persistente será el siguiente paso.)</p>`; })); }
function renderBoard() { board.innerHTML=''; const opts=optionsFor(selected()); for(let y=0;y<8;y++) for(let x=0;x<8;x++) { const cell=document.createElement('button'); cell.type='button'; cell.className='cell'; cell.dataset.label=`${String.fromCharCode(65+x)}${8-y}`; cell.setAttribute('role','gridcell'); const option=opts.find(o=>o.x===x&&o.y===y); if(option) cell.classList.add(`${option.kind}-target`); const unit=at(x,y); if(unit) { const el=document.createElement('div'); el.className=`unit ${unit.team}`; el.innerHTML=`${unit.icon}<span class="hp"><i style="width:${unit.hp/unit.maxHp*100}%"></i></span>`; cell.append(el); } cell.addEventListener('click',()=>cellClick(x,y,option,unit)); board.append(cell); } }
function cellClick(x,y,option,unit) { if(finished||currentTurn!=='player') return; if(option) return perform(selected(),option); if(unit?.team==='player') { selectedId=unit.id; setStatus(`${unit.name}: elige destino, enemigo o captura.`); } else if(unit) setStatus('Ese rival no está a alcance de la unidad seleccionada.'); else { selectedId=null; setStatus('Selecciona una unidad de tu banda.'); } render(); }
function render() { renderBoard(); const people=units.filter(u=>alive(u)); roster.innerHTML=people.map(u=>`<button class="roster-card ${u.team} ${u.id===selectedId?'selected':''}" data-unit="${u.id}"><span class="roster-icon">${u.icon}</span><span><strong>${u.name}</strong><small>${u.type} · ${u.hp}/${u.maxHp} salud</small></span></button>`).join(''); roster.querySelectorAll('[data-unit]').forEach(button=>button.addEventListener('click',()=>{const unit=units.find(u=>u.id===button.dataset.unit);if(unit.team==='player'&&currentTurn==='player'){selectedId=unit.id;setStatus(`${unit.name}: elige destino, enemigo o captura.`);render();}})); const unit=selected(); detail.className='unit-detail'+(unit?'':' empty'); detail.innerHTML=unit?`<h2>${unit.icon} ${unit.name}</h2><div class="stat-row"><span>ARQUETIPO</span><strong>${unit.type}</strong></div><div class="stat-row"><span>SALUD</span><strong>${unit.hp} / ${unit.maxHp}</strong></div><div class="stat-row"><span>DAÑO</span><strong>${unit.damage}</strong></div><div class="ability"><strong>${unit.ability}</strong>${unit.description}</div>`:'Selecciona una unidad para ver sus acciones.'; turnBadge.textContent=currentTurn==='player'?'Tu turno':'Turno rival'; prisonerCount.textContent=prisoners.length; endTurn.disabled=currentTurn!=='player'||finished; }
endTurn.addEventListener('click',()=>{selectedId=null;enemyTurn();}); restart.addEventListener('click',reset); reset();
